- src: https://github.com/Stouts/Stouts.iptables.git
  version: 1.1.2
- src: jdauphant.nginx
- src: ANXS.postgresql
- src: git+https://github.com/ChristopherDavenport/ansible-role-universal-tomcat
  version: f0fe23a3b1541cbc60cabe69afe401f3df07d5d3
